(define balance 100)

(define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               (display balance)
               balance)
        (display "Insufficient funds")))

(display "(withdraw 25): ")
(withdraw 25)
(newline)
(display "(withdraw 25): ")
(withdraw 25)
(newline)
(display "(withdraw 60): ")
(withdraw 60)
(newline)
(display "(withdraw 15): ")
(withdraw 15)
